---
- name: Step 00xxxxx software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"


- name: Configuring satellite Hosts
  hosts: satellites
  become: True
  gather_facts: True
  tasks:

    - import_role:
        name: satellite-public-hostname

    - when: install_satellite
      include_role:
        name: "{{ _role }}"
      loop_control:
        loop_var: _role
      loop:
        - satellite-installation

    - when: configure_satellite
      include_role:
        name: "{{ _role }}"
      loop_control:
        loop_var: _role
      loop:
        - satellite-manage-organization
        - satellite-manage-manifest
        - satellite-manage-repositories
        - satellite-manage-lifecycle
        - satellite-manage-content-view
        - satellite-manage-activationkey
        # - satellite-manage-capsule-certificate


- name: Configure satellite hosts
  hosts: satellite_hosts
  become: True
  gather_facts: True
  tasks:
    - when: configure_satellite
      import_role:
        name: satellite-register-hosts
  vars:
    satellite_hostname: "{{ hostvars['satellite']['publicname'] }}"


- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
