---
- name: Install Satellite Package
  package:
    name: satellite-6.4*.el7*
    state: present
  tags:
    - install_satellite

- name: configure satellite
  command: >-
    satellite-installer --scenario satellite
    --foreman-admin-username {{ satellite_admin }}
    --foreman-admin-password {{ satellite_admin_password }}
    --certs-cname {{inventory_hostname}}
  async: 3600
  poll: 72
  tags:
    - install_satellite
    - setup_satellite
